apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    apps: guestbook-ui
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      name: guestbook-ui
  selector:
    app: guestbook-ui
