apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    apps: guestbook-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 5000
      name: guestbook-ui
  selector:
    app: guestbook-ui
